// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/chuck_norris_fact.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomJokeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category *string `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
}

func (x *GetRandomJokeRequest) Reset() {
	*x = GetRandomJokeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chuck_norris_fact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomJokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomJokeRequest) ProtoMessage() {}

func (x *GetRandomJokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chuck_norris_fact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomJokeRequest.ProtoReflect.Descriptor instead.
func (*GetRandomJokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_chuck_norris_fact_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomJokeRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

type GetRandomJokeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IconUrl string  `protobuf:"bytes,2,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	Url     *string `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Value   string  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetRandomJokeResponse) Reset() {
	*x = GetRandomJokeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chuck_norris_fact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomJokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomJokeResponse) ProtoMessage() {}

func (x *GetRandomJokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chuck_norris_fact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomJokeResponse.ProtoReflect.Descriptor instead.
func (*GetRandomJokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_chuck_norris_fact_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomJokeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRandomJokeResponse) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *GetRandomJokeResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *GetRandomJokeResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_chuck_norris_fact_proto protoreflect.FileDescriptor

var file_proto_chuck_norris_fact_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x75, 0x63, 0x6b, 0x5f, 0x6e, 0x6f,
	0x72, 0x72, 0x69, 0x73, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x68, 0x75, 0x63, 0x6b, 0x6e, 0x6f, 0x72,
	0x72, 0x69, 0x73, 0x22, 0x44, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x76, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x15, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x75, 0x72,
	0x6c, 0x32, 0x80, 0x01, 0x0a, 0x16, 0x43, 0x68, 0x75, 0x63, 0x6b, 0x4e, 0x6f, 0x72, 0x72, 0x69,
	0x73, 0x46, 0x61, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x46, 0x61, 0x63, 0x74, 0x12, 0x28, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x68, 0x75, 0x63, 0x6b, 0x6e, 0x6f, 0x72, 0x72,
	0x69, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4a, 0x6f, 0x6b, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x63, 0x68, 0x75, 0x63, 0x6b, 0x6e, 0x6f, 0x72, 0x72, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_chuck_norris_fact_proto_rawDescOnce sync.Once
	file_proto_chuck_norris_fact_proto_rawDescData = file_proto_chuck_norris_fact_proto_rawDesc
)

func file_proto_chuck_norris_fact_proto_rawDescGZIP() []byte {
	file_proto_chuck_norris_fact_proto_rawDescOnce.Do(func() {
		file_proto_chuck_norris_fact_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_chuck_norris_fact_proto_rawDescData)
	})
	return file_proto_chuck_norris_fact_proto_rawDescData
}

var file_proto_chuck_norris_fact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_chuck_norris_fact_proto_goTypes = []interface{}{
	(*GetRandomJokeRequest)(nil),  // 0: api.v1.chucknorris.GetRandomJokeRequest
	(*GetRandomJokeResponse)(nil), // 1: api.v1.chucknorris.GetRandomJokeResponse
}
var file_proto_chuck_norris_fact_proto_depIdxs = []int32{
	0, // 0: api.v1.chucknorris.ChuckNorrisFactService.GetRandomFact:input_type -> api.v1.chucknorris.GetRandomJokeRequest
	1, // 1: api.v1.chucknorris.ChuckNorrisFactService.GetRandomFact:output_type -> api.v1.chucknorris.GetRandomJokeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chuck_norris_fact_proto_init() }
func file_proto_chuck_norris_fact_proto_init() {
	if File_proto_chuck_norris_fact_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_chuck_norris_fact_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomJokeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chuck_norris_fact_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomJokeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_chuck_norris_fact_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_chuck_norris_fact_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_chuck_norris_fact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chuck_norris_fact_proto_goTypes,
		DependencyIndexes: file_proto_chuck_norris_fact_proto_depIdxs,
		MessageInfos:      file_proto_chuck_norris_fact_proto_msgTypes,
	}.Build()
	File_proto_chuck_norris_fact_proto = out.File
	file_proto_chuck_norris_fact_proto_rawDesc = nil
	file_proto_chuck_norris_fact_proto_goTypes = nil
	file_proto_chuck_norris_fact_proto_depIdxs = nil
}
